### ISSUE TITLE
Crash With JEI

### ISSUE THREAD

**Issue by Shazuli** [tterrag1098/ColorblindHelper#6]
***Hi!***

As someone who is colorblind, I got really excited when I saw this mod. But after I searched for "block" in JEI my game crashed. I have the crash report [here](https://paste.dimdev.org/xikeqerojo.txt).

EnderCore - 1.12.2-0.5.22
ColorblindHelper - 1.12.2-1.1.1.6_beta

**Comment by Shazuli** [comment]
After further testing, it seems to be having issues when displaying blocks/certain items from [OpenComputers](https://minecraft.curseforge.com/projects/opencomputers). This happens in regular inventories such as chests or the Creative Menu and is not limited to [JEI](https://minecraft.curseforge.com/projects/jei?gameCategorySlug=mc-mods&projectID=238222).

**Comment by tterrag1098** [comment]
Thanks for the report, it should be fixed in 1.1.2

**Comment by Shazuli** [comment]
Hi again @tterrag1098.

I just downloaded the newest version of [ColorblindHelpter](https://minecraft.curseforge.com/projects/colorblindhelper/files/2567307) on Curse (1.12.2-1.1.2.7), but the problem still persists. I tried to download the latest [EnderCore](https://minecraft.curseforge.com/projects/endercore) (1.12.2-0.5.30), and delete the configs for both of them, but it still crashes when displaying certain blocks from [OpenComputers](https://minecraft.curseforge.com/projects/opencomputers). Did you upload the wrong version to Curse?
Here is the new [crash-report](https://paste.dimdev.org/erapujuqot.txt).

**Comment by legendblade** [comment]
I'm also having the same issue, specifically with OpenComputers cable (and only the cable object) - same crash as in the linked crash report.

This is a blocking issue for the modpack I'm working on if we want to ship with with ColorblindHelper (Rosethorns/CUTSAshes#7); could this be solved by wrapping the call off to `net.minecraftforge.oredict.OreDictionary.getOreIDs` with a try/catch to provide a way to gracefully fall back? Or, possibly a better long-term solution, adding in a blacklist of items to the config that ColorblindHelper will never try to resolve?

Thanks.

**Comment by tterrag1098** [comment]
Should be fixed now https://minecraft.curseforge.com/projects/colorblindhelper/files/2728219

**Comment by legendblade** [comment]
Unfortunately still occurring even after updating; tested both in the existing pack and in a brand new profile with just:
- Minecraft 1.12.2
- Forge 14.23.5.2838
- OpenComputers: 1.7.4.153
- EnderCore: 1.12.2-0.5.57
- ColorblindHelper: 1.12.2-1.1.2.8
- JEI: 4.15.0.268

Crashlogs:
- Crash from JEI: https://paste.dimdev.org/ihewanufam.cs
- Crash from Creative Tab: https://paste.dimdev.org/uqowazayed.cs

**Comment by tterrag1098** [comment]
What does your JSON config look like?

**Comment by legendblade** [comment]
With the new empty profile, it was the default config:
[colorblind.json.txt](https://github.com/tterrag1098/ColorblindHelper/files/3317187/colorblind.json.txt)

**Comment by tterrag1098** [comment]
Could you try this version? I don't have a great way to verify the fix, but this should totally side-step the issue https://ci.tterrag.com/job/ColorblindHelper-1.12/9/

**Comment by legendblade** [comment]
Same crash in both cases (except for it being on ItemKey.java line 55 instead of 66). :(

**Comment by tterrag1098** [comment]
Can I have the exact crash report?

**Comment by tterrag1098** [comment]
Actually, can you give the entire log?

**Comment by legendblade** [comment]
- Creative crash log: https://paste.dimdev.org/ahunizekup.cs
- JEI crash log: https://paste.dimdev.org/uxulotuqel.cs
- Full latest.log: https://paste.dimdev.org/zotukifaqe.md

**Comment by tterrag1098** [comment]
This is no longer making sense, something is attempting to draw an empty stack, but somehow this stack doesn't actually report as empty? It should be impossible to create an ItemKey for an empty stack, but somehow it's still happening. Can you try this build where I've added even more sanity checks? https://ci.tterrag.com/job/ColorblindHelper-1.12/10/

**Comment by legendblade** [comment]
Sorry for the delay, had to unbury myself from cats.

Sadly, another crash - https://paste.dimdev.org/ihuvozofow.md

Really, really sorry that this has been such a hassle.
